Remove 3 unsafe blocks
SeaLoong/drcom4scut pull request #12
Opened 2020-11-19 15:46 UTC by cq01

考虑到log4rs已经引入crc32fast依赖，是否该使用crc32fast代替手写crc?
去掉3个unsafe块并用upx压缩后程序体积反而变小，或许safe给了编译器更大的优化空间

2020-11-20 02:53 UTC, SeaLoong commented on src/udp/packet.rs
> +    let acc = (0..len).map(|x| x << 2).fold([0u8; 4], |acc, i| {
考虑直接使用crc32fast库来计算？

2020-11-20 02:53 UTC, SeaLoong commented on src/udp/packet.rs
> +    let acc = (0..20)
同样考虑使用crc32fast

2020-11-20 02:54 UTC, SeaLoong requested changes
计算crc32和crc16的部分可以改用crc32fast库的实现

2020-11-23 15:31 UTC, cq01 commented
crc32fast并没实现crc16，而且这crc的计算还有副作用，我实在不知道该怎么改

2020-11-23 15:38 UTC, SeaLoong commented
crc16可以用crc32算出来。
副作用是啥，我看看改一下。

2020-11-23 16:43 UTC, cq01 commented
我刚刚拿crc32fast算了一下，结果完全不对，这真的只是简单异或，把函数名和注释改一下吧，太误导人了

2020-11-24 12:35 UTC, cq01 commented
大哥，你是不是忘了合并？

2020-11-24 15:04 UTC, merged